import type { LobsterCardData } from '@/components/nfa/LobsterCard';
import { nativeSymbol } from '@/lib/format';

/**
 * Mock world state data for demo mode
 */
export const mockWorldState = {
  rewardMultiplier: '1.20x',
  pkStakeLimit: '5,000 CLW',
  mutationBonus: '1.15x',
  dailyCostMultiplier: '0.90x',
  activeEvents: ['GOLDEN_AGE'],
};

/**
 * Mock CLW token data for demo mode
 */
export const mockTokenInfo = {
  price: `0.0025 ${nativeSymbol}`,
  graduated: false,
  totalSupply: '100,000,000 CLW',
  holders: 1_284,
  marketCap: `250,000 ${nativeSymbol}`,
};

/**
 * Lobster name generator — 30 prefixes × 30 suffixes = 900 unique names (covers 888 genesis)
 */
const NAME_PREFIXES = [
  '赤', '铁', '深', '暗', '烈', '冰', '雷', '幻', '焰', '钛',
  '碎', '锈', '虹', '磁', '熔', '霜', '棱', '涡', '潜', '砂',
  '极', '白', '灰', '黑', '星', '浪', '雾', '夜', '残', '荆',
];
const NAME_SUFFIXES = [
  '潮', '光', '壳', '刃', '弦', '影', '尘', '骨', '鸣', '晶',
  '渊', '涌', '锋', '响', '弧', '音', '流', '沙', '岩', '芒',
  '风', '雨', '棘', '甲', '隼', '爪', '瞳', '烬', '镜', '脉',
];

/**
 * Generate rich mock lobster data for demo mode
 */
export function generateMockLobsters(): LobsterCardData[] {
  const mocks: LobsterCardData[] = [];

  // Mythic (1) — rarity 4
  mocks.push({
    tokenId: 1,
    rarity: 4,
    shelter: 7,
    level: 50,
    active: true,
    vaultURI: '',
    isOwned: false,
  });

  // Legendary (4) — rarity 3
  for (let i = 2; i <= 5; i++) {
    mocks.push({
      tokenId: i,
      rarity: 3,
      shelter: i % 8,
      level: 30 + i * 3,
      active: true,
      vaultURI: '',
      isOwned: i === 3,
    });
  }

  // Epic (8) — rarity 2
  for (let i = 6; i <= 13; i++) {
    mocks.push({
      tokenId: i,
      rarity: 2,
      shelter: i % 8,
      level: 15 + i * 2,
      active: i % 3 !== 0,
      vaultURI: '',
      isOwned: i === 8,
    });
  }

  // Rare (15) — rarity 1
  for (let i = 14; i <= 28; i++) {
    mocks.push({
      tokenId: i,
      rarity: 1,
      shelter: i % 8,
      level: 5 + (i % 20),
      active: i % 4 !== 0,
      vaultURI: '',
      isOwned: i === 15 || i === 22,
    });
  }

  // Common (20) — rarity 0
  for (let i = 29; i <= 48; i++) {
    mocks.push({
      tokenId: i,
      rarity: 0,
      shelter: i % 8,
      level: 1 + (i % 10),
      active: i % 5 !== 0,
      vaultURI: '',
      isOwned: false,
    });
  }

  return mocks;
}

/**
 * Get lobster name by token ID.
 * Uses token-names.json (generated by assign-images.ts) when available,
 * falls back to LOBSTER_NAMES for demo/unassigned tokens.
 */
import tokenNamesData from '@/lib/token-names.json';
const TOKEN_NAMES: Record<string, { name: string; rarity: string; imageId: number }> = tokenNamesData;

export function getLobsterName(tokenId: number): string {
  const entry = TOKEN_NAMES[String(tokenId)];
  if (entry) return entry.name;
  // Fallback for tokenIds > 888: combinatorial 30×30 = 900 unique names
  const idx = tokenId - 1;
  const prefix = NAME_PREFIXES[Math.floor(idx / NAME_SUFFIXES.length) % NAME_PREFIXES.length];
  const suffix = NAME_SUFFIXES[idx % NAME_SUFFIXES.length];
  return prefix + suffix;
}

/** @deprecated Use getLobsterName instead */
export function getMockLobsterName(tokenId: number): string {
  return getLobsterName(tokenId);
}

/**
 * Mock DNA attributes for lobster detail page
 */
export function getMockDNA(tokenId: number) {
  // Deterministic "random" based on tokenId
  const seed = tokenId * 7919;
  const attr = (offset: number) => ((seed + offset * 1301) % 100);
  return {
    STR: attr(0),
    DEX: attr(1),
    INT: attr(2),
    CON: attr(3),
    WIS: attr(4),
    CHA: attr(5),
  };
}

/**
 * Mock personality traits
 */
export function getMockPersonality(tokenId: number) {
  const seed = tokenId * 3571;
  const v = (offset: number) => ((seed + offset * 997) % 100);
  return {
    aggressive: v(0),
    curious: v(1),
    social: v(2),
    cautious: v(3),
    creative: v(4),
  };
}
